import Head from 'next/head'
import Image from 'next/image'
import Features from '../Components/Features'
import Integration from '../Components/Integration'
import Landing from '../Components/Landing'
import Navbar from '../Components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main>
      <Navbar/>
      <Landing/>
      <Features/>
      <Integration/>
    </main>

    
    </div>
  )
}
